fix

diff --git a/src/ulib/net/server/plugin/usp/usp_compile.sh.in b/src/ulib/net/server/plugin/usp/usp_compile.sh.in
--- a/src/ulib/net/server/plugin/usp/usp_compile.sh.in
+++ b/src/ulib/net/server/plugin/usp/usp_compile.sh.in
@@ -2,21 +2,54 @@
 
 # ULib - C++ application development framework
 # Version: @ULIB_VERSION@
+#
+# Ex: usp_compile.sh -i /home/user/project/include -o /home/user/project/build
+#
+# -i local include directory
+# -o output filepath for the .so
+#
+# It would be best if usp_compile copied the .usp to the build directory first and then compiled it.
+# This would prevent the source directory from being polluted and ensures that the usp file is in the build directory for userver to alias. 
 
-prefix=@prefix@
-libdir=@libdir@
-includedir=@includedir@
-exec_prefix=@exec_prefix@
+local_build=""
+local_includedir=""
+while getopts "i:o:" opt; do
+    case $opt in
+        i)
+	         local_includedir=-I$OPTARG
+            echo ${local_includedir}
+	         ;;
+        o)
+	         local_build=$OPTARG
+            echo ${local_build}
+	         ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            exit 1
+            ;;
+        :)
+            echo "Option -$OPTARG requires an argument." >&2
+            exit 1
+            ;;
+    esac
+done
+shift $(( OPTIND - 1 ))
 
 if [ -z "$1" ]; then
 	exit 1
 fi
 
 dirn=`dirname $1`
-basen=`basename $1`
+basen=$(basename $1 .usp)
 
-#if [ -n "$dirn" ]; then
-#fi
+file="$dirn/$basen"
+
+if [ -n "$local_build" ]; then
+	cp $file.usp $local_build
+	file=$basen
+	dirn=$local_build
+	cd $local_build
+fi
 
 libsuffix=$2
 test "$libsuffix" || libsuffix=so
@@ -24,10 +57,10 @@ test "$libsuffix" || libsuffix=so
 export UMEMPOOL="0,0,0,48,-20,-20,-20,-20,0"
 export PATH="/sbin:/usr/sbin:/usr/local/sbin:/bin:/usr/bin:/usr/local/bin"
 
-${prefix}/bin/usp_translator $1.usp &&
-${prefix}/bin/usp_libtool.sh --silent --tag=CXX --mode=compile \
-	@CXX@ -I${includedir} -DHAVE_CONFIG_H @CPPFLAGS@ @CXXFLAGS@ @USP_FLAGS@ -MT $basen.lo -MD -MP -c -o $basen.lo $basen.cpp &&
-${prefix}/bin/usp_libtool.sh --silent --tag=CXX --mode=link \
-	@CXX@ @CPPFLAGS@ @LDFLAGS@ @USP_LDFLAGS@ -o $basen.la -rpath ${prefix}/libexec/ulib/usp \
+@ULIB_PREFIXDIR@/bin/usp_translator $file.usp &&
+@ULIB_PREFIXDIR@/bin/usp_libtool.sh --silent --tag=CXX --mode=compile \
+	@CXX@ ${local_includedir} -IULIB_PREFIXDIR@/include -DHAVE_CONFIG_H @CPPFLAGS@ @CXXFLAGS@ @USP_FLAGS@ -MT $basen.lo -MD -MP -c -o $basen.lo $basen.cpp &&
+@ULIB_PREFIXDIR@/bin/usp_libtool.sh --silent --tag=CXX --mode=link \
+	@CXX@ @CPPFLAGS@ @LDFLAGS@ @USP_LDFLAGS@ -o $basen.la -rpath @ULIB_MODULEDIR@ \
 	-module -export-dynamic -avoid-version -no-undefined $basen.lo @USP_LIBS@ -l@ULIB@ @ULIB_LIBS@ &&
-mv $1.usp .libs; rm -rf $basen.d $basen.la $basen.lo $basen.o $basen.cpp; mv .libs/${basen}.usp .libs/${basen}.$libsuffix ${dirn}; rm -rf .libs
+mv $file.usp .libs; rm -rf $basen.d $basen.la $basen.lo $basen.o $basen.cpp; mv .libs/${basen}.usp .libs/${basen}.${libsuffix} ${dirn}; rm -rf .libs
